### ISSUE TITLE
Problem Line Format "Normalizer"

### ISSUE THREAD

**Issue by electronsandstuff** [electronsandstuff/ParetoBench#11]
With the string based problem serialization format, it is possible for many strings to refer to the same problem. For instance `WFG1 (n=16, m=2)` and `WFG1 (m=2, n=16)` are the same and so is `WFG1 (m = 2, n = 16)` (whitespace difference). This can cause issues when using the strings as a stand-in for the problems in stuff like pandas dataframes or the keys of dictionaries.

One way to solve this problem is to "normalize" the problem strings into a standard format so that identical problems translate into identical strings. To complete this issue, I would like to add a function to the package which performs this type of normalization. Some requirements follow.

- Strings that represent identical problems must be converted into identical "normalized" strings.
- The method should work on both problems that are registered to ParetoBench and ones that are not. That is, the function should work on arbitrary strings of the type `<NAME> (key1=val1, key2=val2, ...)`.
- When it is used on a problem registered to the ParetoBench, the function should handle default parameters. For example, it should know that `WFG1 (n=16, m=2)` and `WFG1 (n=16, m=2, k=2)` are the same since `k=2` is the default setting for `WFG1`.

I believe this can be achieved by creating the problem object from the string (if registered) or deserializing it into a name and a dict (if not registered) and then serializing it back. As long as the serializer creates identical output for identical input this will guarantee a standard format. I don't think this is actually the case right now since I use dict's `.items()` method and dictionaries are unordered. I could meet this assumption, however, by ordering the keys (sorting alphabetically, for instance).

# TODO

- [ ] Modify `dumps(...)` so that it produces identical output for identical input regardless of dictionary implementation details. (IE sort the keys)
- [ ] Create a unit test to confirm that strings from `dumps(...)` are really identical when identical dicts are passed regardless of how the dict is constructed and what datatypes are in it. Try to permute the order in which keys are added, for instance.
- [ ] Create function to make normalize problem name
- [ ] Add unit tests to for normalization function
  - [ ] Registered problem
  - [ ] Non-registered problem
  - [ ] Default values
