### ISSUE TITLE
Serialization/Deserialization of Problems

### ISSUE THREAD

**Issue by electronsandstuff** [electronsandstuff/ParetoBench#2]
Problems should be serializable. Instantiating problems should also be able to be done through a basic string format such as `<problem_name> (<p1>=<val1>, <p2>=<val2>, ...)` to enable easy integration with config files, etc.

For data validation/serialization/deserialization I think I should use pydantic. This will make it easy to define the datatypes each of the problems use. Then I can have additional methods/functions for my custom single line format.

## TODO

- [x] Migrate all of the problem objects to be pydantic classes
  - [x] CF
  - [x] CTP
  - [x] DTLZ
  - [x] Misc
  - [x] WFG
  - [x] ZDT
- [x] Create the custom single line serialization format
  - [x] Create serializer (dict -> str) and have it support int, bool, str, float
  - [x] Create deserializer
  - [x] Write up a standard for the format somewhere
  - [x] Support empty string
- [x] Write functions in `factory.py` and problem classes which save/load problems from single line format
  - [x] Document the standard for single line problem format somewhere
  - [x] Write the serializer
  - [x] Write the deserializer
  - [x] Implement deserialization of names without parameters (use all default params)
- [x] Check datatypes for CF `a` parameter
- [x] Review `split_unqoted` to see if there's an existing python version w/o a tight loop.
- [x] Verify that all of the parameters used in the problem objects match their literature names. Standardize common ones like input/output dimension.
  - [x] CF
  - [x] CTP
  - [x] DTLZ
  - [x] Misc
  - [x] WFG
  - [x] ZDT
- [x] Use custom exception classes in serializer/deserializer
- [x] More unit testsing
  - [x] Add unittests to confirm that problem names and parameters don't have "bad characters" for serialization format
  - [x] Add randomization of problems to save load test
  - [x] Add unit test for white space in serialization formats
  - [x] Add unit test to make random classes, serialize, then deserialize, and check results.
  - [x] Write unit tests to load problems from line objects.
  - [x] Check that converting objects without parameters to lines doesn't include extra empty parenthesis.
  - [x] Unit test loading problems with name only and empty parenthesis.
- [x] Have notebook or script to print all default objects and their serializations to make sure it looks OK
